node_id=1
node_name='zabbix-db'
conninfo='host=192.168.200.170 port=5432 dbname=repmgr user=repmgr'
data_directory='/var/lib/postgresql/data'
use_replication_slots=yes
failover=automatic
promote_command='repmgr standby promote -f /etc/repmgr.conf'
follow_command='repmgr standby follow -f /etc/repmgr.conf'
